/**
 * Topics and sub-topics for the newsletter subscription flow.
 * Single source of truth — mirrors backend/tools/research_topic.py TOPICS_CONFIG.
 *
 * Usage in dropdowns:
 *   - First dropdown:  Object.keys(TOPICS_CONFIG)       → topic labels
 *   - Second dropdown: TOPICS_CONFIG[selectedTopic]     → sub-topic labels
 */

export const TOPICS_CONFIG = {
  "AI & Technology": [
    "Large Language Models",
    "ChatGPT & OpenAI",
    "Claude & Anthropic",
    "Gemini & Google AI",
    "Open Source AI",
    "AI Agents & Automation",
    "Robotics & Automation",
    "Computer Vision",
    "Generative AI",
    "AI in Healthcare",
    "AI in Education",
    "AI in Finance",
    "AI Ethics & Policy",
    "AI Regulation",
    "Cybersecurity",
    "Data Privacy & GDPR",
    "Hacking & Data Breaches",
    "Cloud Computing",
    "AWS & Amazon",
    "Google Cloud",
    "Microsoft Azure",
    "Semiconductors & Chips",
    "Quantum Computing",
    "Self-Driving Cars",
    "Blockchain & Web3",
    "AR & VR",
    "5G & Connectivity",
    "Smart Devices & IoT",
    "Tech Startups",
    "Tech Layoffs & Jobs",
    "Developer Tools",
    "Open Source Software",
    "Tech Policy & Antitrust",
  ],
  "Geopolitics": [
    "Middle East",
    "Israel-Palestine Conflict",
    "Iran",
    "Russia-Ukraine War",
    "US Politics",
    "US-China Relations",
    "US-Russia Relations",
    "NATO & Defense",
    "Europe",
    "UK Politics",
    "France",
    "Germany",
    "Asia Pacific",
    "China",
    "India",
    "India-Pakistan Relations",
    "Japan",
    "South Korea",
    "North Korea",
    "Southeast Asia",
    "Africa",
    "Latin America",
    "Climate Diplomacy",
    "United Nations",
    "Trade & Tariffs",
    "Sanctions",
    "Nuclear Arms",
    "Terrorism & Extremism",
    "Refugee & Migration Crisis",
    "Human Rights",
    "Espionage & Intelligence",
  ],
  "Cinema": [
    "Hollywood",
    "Bollywood",
    "Telugu Cinema",
    "Tamil Cinema",
    "Malayalam Cinema",
    "Kannada Cinema",
    "Marathi Cinema",
    "Bengali Cinema",
    "Korean Cinema",
    "Chinese Cinema",
    "Japanese Cinema",
    "French Cinema",
    "Independent Films",
    "Documentaries",
    "Animation",
    "Horror Films",
    "Action & Blockbusters",
    "OTT & Streaming",
    "Netflix",
    "Amazon Prime Video",
    "Disney+ & Marvel",
    "Apple TV+ & HBO Max",
    "Oscars & Academy Awards",
    "Cannes Film Festival",
    "BAFTA & Golden Globes",
    "Box Office News",
    "Movie Reviews",
    "Upcoming Releases",
    "Celebrity News",
    "Director Spotlights",
    "Remakes & Sequels",
  ],
  "Sports": [
    "Cricket",
    "Test Cricket",
    "IPL",
    "ICC World Cup",
    "Football",
    "Premier League",
    "La Liga",
    "UEFA Champions League",
    "FIFA World Cup",
    "Formula 1",
    "NASCAR & Motorsports",
    "Basketball",
    "NBA",
    "WNBA",
    "Tennis",
    "Wimbledon",
    "US Open Tennis",
    "French Open",
    "Australian Open",
    "Golf & PGA Tour",
    "Rugby",
    "Olympics",
    "Swimming",
    "Athletics & Track",
    "Boxing",
    "MMA & UFC",
    "Ice Hockey",
    "Baseball & MLB",
    "NFL & American Football",
    "Kabaddi",
    "Badminton",
    "Table Tennis",
    "Esports",
  ],
  "Business & Finance": [
    "Stock Markets",
    "Wall Street & NYSE",
    "NASDAQ & Tech Stocks",
    "Indian Stock Market",
    "Global Markets",
    "Startups & VC",
    "Series A & Fundraising",
    "Unicorns & IPOs",
    "M&A & Acquisitions",
    "Cryptocurrency",
    "Bitcoin",
    "Ethereum",
    "Altcoins & DeFi",
    "NFTs",
    "Economy & Policy",
    "US Economy",
    "Indian Economy",
    "Global Economy",
    "Interest Rates & Fed",
    "Inflation",
    "Oil & Energy Markets",
    "Real Estate",
    "Retail & E-commerce",
    "Banking & Finance",
    "FinTech",
    "Insurance",
    "Supply Chain",
    "Layoffs & Corporate News",
    "ESG & Sustainability",
    "Automotive Industry",
    "Aerospace & Defense",
  ],
  "Science & Environment": [
    "Space Exploration",
    "NASA",
    "SpaceX & Private Space",
    "Mars & Moon Missions",
    "Astronomy & Telescopes",
    "Climate & Environment",
    "Climate Change",
    "Carbon & Emissions",
    "Renewable Energy",
    "Solar & Wind Energy",
    "Biodiversity & Wildlife",
    "Oceans & Marine Life",
    "Deforestation",
    "Extreme Weather",
    "Medicine & Biology",
    "Cancer Research",
    "Vaccines & Immunology",
    "Genetics & Genomics",
    "Neuroscience",
    "Drug Discovery",
    "Disease Outbreaks",
    "Physics & Astronomy",
    "Particle Physics",
    "Nuclear Energy",
    "Quantum Physics",
    "Archaeology",
    "Paleontology",
    "AI in Science",
    "Marine Science",
    "Earthquakes & Geology",
    "Meteorology",
  ],
  "Health & Wellness": [
    "Mental Health",
    "Anxiety & Depression",
    "ADHD & Autism",
    "Mindfulness & Meditation",
    "Therapy & Counseling",
    "Fitness & Nutrition",
    "Weight Loss & Diet",
    "Exercise & Gym",
    "Running & Marathons",
    "Yoga & Pilates",
    "Sleep & Recovery",
    "Sports Nutrition",
    "Vegan & Plant-Based Diet",
    "Medical Research",
    "Cancer Treatment",
    "Heart Health & Cardiology",
    "Diabetes",
    "Women's Health",
    "Men's Health",
    "Children's Health",
    "Senior Health & Aging",
    "Gut Health",
    "Skin Health",
    "Dental Health",
    "COVID & Respiratory Health",
    "Addiction & Recovery",
    "Alternative Medicine",
    "Healthcare Policy",
    "Global Health & WHO",
  ],
  "Gaming & Esports": [
    "Console Gaming",
    "PlayStation",
    "Xbox & Game Pass",
    "Nintendo Switch",
    "PC Gaming",
    "Mobile Gaming",
    "iOS Games",
    "Android Games",
    "Pokémon GO & AR Games",
    "Esports",
    "League of Legends",
    "Valorant",
    "CS2 & Counter-Strike",
    "Dota 2",
    "Fortnite & Battle Royale",
    "Call of Duty",
    "FIFA & Sports Games",
    "RPG & Open World",
    "Horror & Indie Games",
    "Game Reviews & Releases",
    "Game Development",
    "Gaming Hardware & GPUs",
    "VR Gaming",
    "Game Streaming & Twitch",
    "YouTube Gaming",
    "Nintendo & Pokémon News",
    "Game Industry Business",
    "Gaming Controversies",
  ],
  "Culture & Entertainment": [
    "Music",
    "Pop Music",
    "Hip-Hop & Rap",
    "Rock & Metal",
    "K-Pop",
    "Bollywood Music",
    "Music Awards & Grammys",
    "Music Festivals & Concerts",
    "Fashion",
    "High Fashion & Runway",
    "Street Style",
    "Sustainable Fashion",
    "Celebrity Style",
    "Food & Travel",
    "Fine Dining & Restaurants",
    "Street Food & Food Culture",
    "Travel Destinations",
    "Budget Travel",
    "Books & Literature",
    "Fiction & Novels",
    "Non-Fiction & Biography",
    "Fantasy & Sci-Fi",
    "Television & TV Shows",
    "Reality TV",
    "Anime & Manga",
    "Comedy & Stand-Up",
    "Art & Museums",
    "Photography",
    "Theatre & Stage",
    "Celebrity News",
  ],
  "Education & Careers": [
    "EdTech",
    "Online Learning & MOOCs",
    "Coding & Programming Education",
    "AI in Education",
    "K-12 Education",
    "Special Education",
    "Early Childhood Education",
    "Higher Education",
    "Universities & Colleges",
    "MBA & Business School",
    "Medical Education",
    "Engineering & STEM",
    "Liberal Arts",
    "Study Abroad",
    "Scholarships & Financial Aid",
    "Job Market & Careers",
    "Tech Jobs",
    "Remote Work",
    "Internships & Graduate Programs",
    "MBA Careers",
    "Government & Public Sector Jobs",
    "Healthcare Careers",
    "Creative Careers",
    "Entrepreneurship & Freelancing",
    "Career Development",
    "Skills & Certifications",
    "Resume & Interview Tips",
    "Workplace Culture",
    "Diversity & Inclusion",
    "Future of Work",
  ],
};

/** Flat list of all topic names. */
export const ALL_TOPICS = Object.keys(TOPICS_CONFIG);

/** Get sub-topics for a given topic (returns [] if topic not found). */
export const getSubTopics = (topic) => TOPICS_CONFIG[topic] ?? [];

/** Total sub-topic count across all topics. */
export const TOTAL_SUBTOPICS = Object.values(TOPICS_CONFIG)
  .reduce((sum, subs) => sum + subs.length, 0);
